package dto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StudentObject.proto

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StudentObjectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StudentObject)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string surname = 1;</code>
     * @return The surname.
     */
    java.lang.String getSurname();
    /**
     * <code>string surname = 1;</code>
     * @return The bytes for surname.
     */
    com.google.protobuf.ByteString
        getSurnameBytes();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string faculty = 3;</code>
     * @return The faculty.
     */
    java.lang.String getFaculty();
    /**
     * <code>string faculty = 3;</code>
     * @return The bytes for faculty.
     */
    com.google.protobuf.ByteString
        getFacultyBytes();

    /**
     * <code>string group = 4;</code>
     * @return The group.
     */
    java.lang.String getGroup();
    /**
     * <code>string group = 4;</code>
     * @return The bytes for group.
     */
    com.google.protobuf.ByteString
        getGroupBytes();

    /**
     * <code>.google.protobuf.Timestamp dateOfAdmission = 5;</code>
     * @return Whether the dateOfAdmission field is set.
     */
    boolean hasDateOfAdmission();
    /**
     * <code>.google.protobuf.Timestamp dateOfAdmission = 5;</code>
     * @return The dateOfAdmission.
     */
    com.google.protobuf.Timestamp getDateOfAdmission();
    /**
     * <code>.google.protobuf.Timestamp dateOfAdmission = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getDateOfAdmissionOrBuilder();

    /**
     * <code>int32 term = 6;</code>
     * @return The term.
     */
    int getTerm();

    /**
     * <code>bool isStudying = 7;</code>
     * @return The isStudying.
     */
    boolean getIsStudying();
  }
  /**
   * Protobuf type {@code StudentObject}
   */
  public static final class StudentObject extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StudentObject)
      StudentObjectOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StudentObject.newBuilder() to construct.
    private StudentObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StudentObject() {
      surname_ = "";
      name_ = "";
      faculty_ = "";
      group_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StudentObject();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StudentObject(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              surname_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              faculty_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              group_ = s;
              break;
            }
            case 42: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (dateOfAdmission_ != null) {
                subBuilder = dateOfAdmission_.toBuilder();
              }
              dateOfAdmission_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dateOfAdmission_);
                dateOfAdmission_ = subBuilder.buildPartial();
              }

              break;
            }
            case 48: {

              term_ = input.readInt32();
              break;
            }
            case 56: {

              isStudying_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StudentProto.internal_static_StudentObject_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StudentProto.internal_static_StudentObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StudentProto.StudentObject.class, StudentProto.StudentObject.Builder.class);
    }

    public static final int SURNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object surname_;
    /**
     * <code>string surname = 1;</code>
     * @return The surname.
     */
    @java.lang.Override
    public java.lang.String getSurname() {
      java.lang.Object ref = surname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        surname_ = s;
        return s;
      }
    }
    /**
     * <code>string surname = 1;</code>
     * @return The bytes for surname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSurnameBytes() {
      java.lang.Object ref = surname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        surname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FACULTY_FIELD_NUMBER = 3;
    private volatile java.lang.Object faculty_;
    /**
     * <code>string faculty = 3;</code>
     * @return The faculty.
     */
    @java.lang.Override
    public java.lang.String getFaculty() {
      java.lang.Object ref = faculty_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        faculty_ = s;
        return s;
      }
    }
    /**
     * <code>string faculty = 3;</code>
     * @return The bytes for faculty.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFacultyBytes() {
      java.lang.Object ref = faculty_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        faculty_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUP_FIELD_NUMBER = 4;
    private volatile java.lang.Object group_;
    /**
     * <code>string group = 4;</code>
     * @return The group.
     */
    @java.lang.Override
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        group_ = s;
        return s;
      }
    }
    /**
     * <code>string group = 4;</code>
     * @return The bytes for group.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATEOFADMISSION_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp dateOfAdmission_;
    /**
     * <code>.google.protobuf.Timestamp dateOfAdmission = 5;</code>
     * @return Whether the dateOfAdmission field is set.
     */
    @java.lang.Override
    public boolean hasDateOfAdmission() {
      return dateOfAdmission_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp dateOfAdmission = 5;</code>
     * @return The dateOfAdmission.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getDateOfAdmission() {
      return dateOfAdmission_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateOfAdmission_;
    }
    /**
     * <code>.google.protobuf.Timestamp dateOfAdmission = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getDateOfAdmissionOrBuilder() {
      return getDateOfAdmission();
    }

    public static final int TERM_FIELD_NUMBER = 6;
    private int term_;
    /**
     * <code>int32 term = 6;</code>
     * @return The term.
     */
    @java.lang.Override
    public int getTerm() {
      return term_;
    }

    public static final int ISSTUDYING_FIELD_NUMBER = 7;
    private boolean isStudying_;
    /**
     * <code>bool isStudying = 7;</code>
     * @return The isStudying.
     */
    @java.lang.Override
    public boolean getIsStudying() {
      return isStudying_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSurnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, surname_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getFacultyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, faculty_);
      }
      if (!getGroupBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, group_);
      }
      if (dateOfAdmission_ != null) {
        output.writeMessage(5, getDateOfAdmission());
      }
      if (term_ != 0) {
        output.writeInt32(6, term_);
      }
      if (isStudying_ != false) {
        output.writeBool(7, isStudying_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSurnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, surname_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getFacultyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, faculty_);
      }
      if (!getGroupBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, group_);
      }
      if (dateOfAdmission_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getDateOfAdmission());
      }
      if (term_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, term_);
      }
      if (isStudying_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, isStudying_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof StudentProto.StudentObject)) {
        return super.equals(obj);
      }
      StudentProto.StudentObject other = (StudentProto.StudentObject) obj;

      if (!getSurname()
          .equals(other.getSurname())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getFaculty()
          .equals(other.getFaculty())) return false;
      if (!getGroup()
          .equals(other.getGroup())) return false;
      if (hasDateOfAdmission() != other.hasDateOfAdmission()) return false;
      if (hasDateOfAdmission()) {
        if (!getDateOfAdmission()
            .equals(other.getDateOfAdmission())) return false;
      }
      if (getTerm()
          != other.getTerm()) return false;
      if (getIsStudying()
          != other.getIsStudying()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SURNAME_FIELD_NUMBER;
      hash = (53 * hash) + getSurname().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + FACULTY_FIELD_NUMBER;
      hash = (53 * hash) + getFaculty().hashCode();
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getGroup().hashCode();
      if (hasDateOfAdmission()) {
        hash = (37 * hash) + DATEOFADMISSION_FIELD_NUMBER;
        hash = (53 * hash) + getDateOfAdmission().hashCode();
      }
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + getTerm();
      hash = (37 * hash) + ISSTUDYING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsStudying());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static StudentProto.StudentObject parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StudentProto.StudentObject parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StudentProto.StudentObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StudentProto.StudentObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StudentProto.StudentObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StudentProto.StudentObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StudentProto.StudentObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StudentProto.StudentObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static StudentProto.StudentObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static StudentProto.StudentObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static StudentProto.StudentObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static StudentProto.StudentObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(StudentProto.StudentObject prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StudentObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StudentObject)
        StudentProto.StudentObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StudentProto.internal_static_StudentObject_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StudentProto.internal_static_StudentObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                StudentProto.StudentObject.class, StudentProto.StudentObject.Builder.class);
      }

      // Construct using test.StudentProto.StudentObject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        surname_ = "";

        name_ = "";

        faculty_ = "";

        group_ = "";

        if (dateOfAdmissionBuilder_ == null) {
          dateOfAdmission_ = null;
        } else {
          dateOfAdmission_ = null;
          dateOfAdmissionBuilder_ = null;
        }
        term_ = 0;

        isStudying_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StudentProto.internal_static_StudentObject_descriptor;
      }

      @java.lang.Override
      public StudentProto.StudentObject getDefaultInstanceForType() {
        return StudentProto.StudentObject.getDefaultInstance();
      }

      @java.lang.Override
      public StudentProto.StudentObject build() {
        StudentProto.StudentObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public StudentProto.StudentObject buildPartial() {
        StudentProto.StudentObject result = new StudentProto.StudentObject(this);
        result.surname_ = surname_;
        result.name_ = name_;
        result.faculty_ = faculty_;
        result.group_ = group_;
        if (dateOfAdmissionBuilder_ == null) {
          result.dateOfAdmission_ = dateOfAdmission_;
        } else {
          result.dateOfAdmission_ = dateOfAdmissionBuilder_.build();
        }
        result.term_ = term_;
        result.isStudying_ = isStudying_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof StudentProto.StudentObject) {
          return mergeFrom((StudentProto.StudentObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(StudentProto.StudentObject other) {
        if (other == StudentProto.StudentObject.getDefaultInstance()) return this;
        if (!other.getSurname().isEmpty()) {
          surname_ = other.surname_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getFaculty().isEmpty()) {
          faculty_ = other.faculty_;
          onChanged();
        }
        if (!other.getGroup().isEmpty()) {
          group_ = other.group_;
          onChanged();
        }
        if (other.hasDateOfAdmission()) {
          mergeDateOfAdmission(other.getDateOfAdmission());
        }
        if (other.getTerm() != 0) {
          setTerm(other.getTerm());
        }
        if (other.getIsStudying() != false) {
          setIsStudying(other.getIsStudying());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        StudentProto.StudentObject parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (StudentProto.StudentObject) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object surname_ = "";
      /**
       * <code>string surname = 1;</code>
       * @return The surname.
       */
      public java.lang.String getSurname() {
        java.lang.Object ref = surname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          surname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string surname = 1;</code>
       * @return The bytes for surname.
       */
      public com.google.protobuf.ByteString
          getSurnameBytes() {
        java.lang.Object ref = surname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          surname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string surname = 1;</code>
       * @param value The surname to set.
       * @return This builder for chaining.
       */
      public Builder setSurname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        surname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string surname = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSurname() {
        
        surname_ = getDefaultInstance().getSurname();
        onChanged();
        return this;
      }
      /**
       * <code>string surname = 1;</code>
       * @param value The bytes for surname to set.
       * @return This builder for chaining.
       */
      public Builder setSurnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        surname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object faculty_ = "";
      /**
       * <code>string faculty = 3;</code>
       * @return The faculty.
       */
      public java.lang.String getFaculty() {
        java.lang.Object ref = faculty_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          faculty_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string faculty = 3;</code>
       * @return The bytes for faculty.
       */
      public com.google.protobuf.ByteString
          getFacultyBytes() {
        java.lang.Object ref = faculty_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          faculty_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string faculty = 3;</code>
       * @param value The faculty to set.
       * @return This builder for chaining.
       */
      public Builder setFaculty(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        faculty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string faculty = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFaculty() {
        
        faculty_ = getDefaultInstance().getFaculty();
        onChanged();
        return this;
      }
      /**
       * <code>string faculty = 3;</code>
       * @param value The bytes for faculty to set.
       * @return This builder for chaining.
       */
      public Builder setFacultyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        faculty_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object group_ = "";
      /**
       * <code>string group = 4;</code>
       * @return The group.
       */
      public java.lang.String getGroup() {
        java.lang.Object ref = group_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          group_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string group = 4;</code>
       * @return The bytes for group.
       */
      public com.google.protobuf.ByteString
          getGroupBytes() {
        java.lang.Object ref = group_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          group_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string group = 4;</code>
       * @param value The group to set.
       * @return This builder for chaining.
       */
      public Builder setGroup(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string group = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroup() {
        
        group_ = getDefaultInstance().getGroup();
        onChanged();
        return this;
      }
      /**
       * <code>string group = 4;</code>
       * @param value The bytes for group to set.
       * @return This builder for chaining.
       */
      public Builder setGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        group_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp dateOfAdmission_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateOfAdmissionBuilder_;
      /**
       * <code>.google.protobuf.Timestamp dateOfAdmission = 5;</code>
       * @return Whether the dateOfAdmission field is set.
       */
      public boolean hasDateOfAdmission() {
        return dateOfAdmissionBuilder_ != null || dateOfAdmission_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp dateOfAdmission = 5;</code>
       * @return The dateOfAdmission.
       */
      public com.google.protobuf.Timestamp getDateOfAdmission() {
        if (dateOfAdmissionBuilder_ == null) {
          return dateOfAdmission_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateOfAdmission_;
        } else {
          return dateOfAdmissionBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp dateOfAdmission = 5;</code>
       */
      public Builder setDateOfAdmission(com.google.protobuf.Timestamp value) {
        if (dateOfAdmissionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dateOfAdmission_ = value;
          onChanged();
        } else {
          dateOfAdmissionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateOfAdmission = 5;</code>
       */
      public Builder setDateOfAdmission(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (dateOfAdmissionBuilder_ == null) {
          dateOfAdmission_ = builderForValue.build();
          onChanged();
        } else {
          dateOfAdmissionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateOfAdmission = 5;</code>
       */
      public Builder mergeDateOfAdmission(com.google.protobuf.Timestamp value) {
        if (dateOfAdmissionBuilder_ == null) {
          if (dateOfAdmission_ != null) {
            dateOfAdmission_ =
              com.google.protobuf.Timestamp.newBuilder(dateOfAdmission_).mergeFrom(value).buildPartial();
          } else {
            dateOfAdmission_ = value;
          }
          onChanged();
        } else {
          dateOfAdmissionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateOfAdmission = 5;</code>
       */
      public Builder clearDateOfAdmission() {
        if (dateOfAdmissionBuilder_ == null) {
          dateOfAdmission_ = null;
          onChanged();
        } else {
          dateOfAdmission_ = null;
          dateOfAdmissionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp dateOfAdmission = 5;</code>
       */
      public com.google.protobuf.Timestamp.Builder getDateOfAdmissionBuilder() {
        
        onChanged();
        return getDateOfAdmissionFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp dateOfAdmission = 5;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getDateOfAdmissionOrBuilder() {
        if (dateOfAdmissionBuilder_ != null) {
          return dateOfAdmissionBuilder_.getMessageOrBuilder();
        } else {
          return dateOfAdmission_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : dateOfAdmission_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp dateOfAdmission = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getDateOfAdmissionFieldBuilder() {
        if (dateOfAdmissionBuilder_ == null) {
          dateOfAdmissionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getDateOfAdmission(),
                  getParentForChildren(),
                  isClean());
          dateOfAdmission_ = null;
        }
        return dateOfAdmissionBuilder_;
      }

      private int term_ ;
      /**
       * <code>int32 term = 6;</code>
       * @return The term.
       */
      @java.lang.Override
      public int getTerm() {
        return term_;
      }
      /**
       * <code>int32 term = 6;</code>
       * @param value The term to set.
       * @return This builder for chaining.
       */
      public Builder setTerm(int value) {
        
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 term = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerm() {
        
        term_ = 0;
        onChanged();
        return this;
      }

      private boolean isStudying_ ;
      /**
       * <code>bool isStudying = 7;</code>
       * @return The isStudying.
       */
      @java.lang.Override
      public boolean getIsStudying() {
        return isStudying_;
      }
      /**
       * <code>bool isStudying = 7;</code>
       * @param value The isStudying to set.
       * @return This builder for chaining.
       */
      public Builder setIsStudying(boolean value) {
        
        isStudying_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isStudying = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsStudying() {
        
        isStudying_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:StudentObject)
    }

    // @@protoc_insertion_point(class_scope:StudentObject)
    private static final StudentProto.StudentObject DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new StudentProto.StudentObject();
    }

    public static StudentProto.StudentObject getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StudentObject>
        PARSER = new com.google.protobuf.AbstractParser<StudentObject>() {
      @java.lang.Override
      public StudentObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StudentObject(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StudentObject> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StudentObject> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public StudentProto.StudentObject getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StudentObject_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StudentObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023StudentObject.proto\032\037google/protobuf/t" +
      "imestamp.proto\"\245\001\n\rStudentObject\022\017\n\007surn" +
      "ame\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\017\n\007faculty\030\003 \001(\t" +
      "\022\r\n\005group\030\004 \001(\t\0223\n\017dateOfAdmission\030\005 \001(\013" +
      "2\032.google.protobuf.Timestamp\022\014\n\004term\030\006 \001" +
      "(\005\022\022\n\nisStudying\030\007 \001(\010B\020\n\000B\014StudentProto" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_StudentObject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StudentObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StudentObject_descriptor,
        new java.lang.String[] { "Surname", "Name", "Faculty", "Group", "DateOfAdmission", "Term", "IsStudying", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
